# Base config file which stores the default parameters which apply to all model configurations
---

# Mode to use for debugging/development; this only uses a few samples in in the train/val dataset
# to quickly run the code
debug_mode: False

# Base directory for output files; do not change this 
output_path: "output/train"

# Experiment name; this will be used for the output directory; use "development" when developing
exp_name: "development"

# Parameters for the dataset class
dataset:
  # Name of dataset
  name: "cifar10"

  # Path to the root of the dataset
  root: "/mnt/c/Users/bsele/Documents/Datasets/cifar10"

  # Number of CPU processes the next sample in the dataset; use 0 to only use the main process
  num_workers: 4

# Model to be trained during diffusion; later I should make this its own config file
model_name: unet

# params for the model
model_params:

  # Params for UNet model; see diffusion.models.unet for param descriptions
  unet:
  # TODO: comment these params
    dim: 64
    dim_mults: [1, 2, 4, 8]

  # ema decay TODO write more on this
  ema_decay: 0.995
  

train:

  # Configurations for optimization parameters such as the optmizier and lr scheduler
  optimizaiton_config: "opt_config_1"

  batch_size: 4

  # The step to start on; ddpm doesn't seem to use epochs and uses steps instead;
  start_steps: 1
  steps: 700000

  # Number of steps to checkpoint after; use 'null' to turn off checkpointing
  ckpt_steps: 1000

# Might remove if not used
validation:
  batch_size: 4

# GPU parameters
cuda:

  # List of GPU devices to use
  gpus: [0]

# Logging parameters
logging:

  # Log the train progress every n steps
  train_steps_freq: 20

# Reproducibility information
reproducibility:
  seed: 42


# Params for training objects

# Adam optimizer parameters defined here: https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/config/yolov3.cfg
opt_config_1:
  optimizer: "adam"

  learning_rate: 8e-5 # Lucidrains uses 8e-5 in the README

  # L2 regulartization penalty to add to the loss function: 
  weight_decay: 0.0